name: lint

on: [push, pull_request]

jobs:
  lint:
    name: Run linters

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - run: npm ci

      - run: npm run lint

      - run: npm run prettier:check
