name: test

on: [push, pull_request]

jobs:
  test:
    name: Run tests and upload coverage reports

    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest, windows-latest]
        test-set: [ava]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      - name: Generate coverage report with ${{ matrix.test-set }}
        run: npm run test-cover:${{ matrix.test-set }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
          flags: unit,${{ matrix.test-set }},${{ matrix.os }}
          fail_ci_if_error: true
          verbose: true
