name: test

on: [push, pull_request]

jobs:
  test:
    name: Run tests and upload coverage reports

    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest, windows-latest]
        test-set: [ava, jest, mocha]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci

      - name: Generate coverage report with ${{ matrix.test-set }}
        run: npm run test-cover:${{ matrix.test-set }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
          flags: unit,${{ matrix.test-set }},${{ matrix.os }}
          fail_ci_if_error: true
          verbose: true
